apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-kc8w
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0006-tenant/tkrw-pr712-0075-0006-app/devfile-sample-kc8w@sha256:683be6893fe258e2a840c22acc27be893d7af07e434d052bcbd3a6e2a20bc566
        name: my-nodejs
        resources: {}
status: {}
